In [1]:
import numpy as np

In [ ]:
# Numpy - Numerical python
# ndarray = n-dimensional array

In [6]:
np1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(np1)
print(np1.shape) # length of the array

[0 1 2 3 4 5 6 7 8 9]
(10,)


In [8]:
# Range
np2 = np.arange(10) # genreate a array within the  range specified
print(np2)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
# Step
np3 = np.arange(0,10, 2)
print(np3)

[0 2 4 6 8]


In [14]:
np4 = np.zeros(10)
np4

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
# multidimensional zeros
np5 = np.zeros((3, 4))
np5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
# full
np6 = np.full((10), 6)
np6

array([6, 6, 6, 6, 6, 6, 6, 6, 6, 6])

In [23]:
# Multidimensional full
np7 = np.full(((2, 8)), 6)
np7

array([[6, 6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6, 6]])

In [26]:
# Convert python lists to numpy
my_list = [0, 1, 2, 3, 4, 5, 6, 7]
np8 = np.array(my_list)
print(np8)

[0 1 2 3 4 5 6 7]
