In [2]:
import numpy as np

In [5]:
# Creating a basic array
a = np.zeros(2)
a
b = np.ones(3)
b
c = np.empty(2)
print(c)

[0. 0.]


In [9]:
np1 = np.arange(2, 9, 2)
np1
# Array spacing evenly
np2 = np.linspace(0, 10, num=5)
print(np2)

[ 0.   2.5  5.   7.5 10. ]


In [13]:
# Specifying your data type
np3 = np.ones(2, dtype=np.float64)
np3
np4 = np.ones(2, dtype=np.int64)
np4

array([1, 1], dtype=int64)

In [12]:
# Adding, Removing and Sorting
arr = np.array([2, 1, 3, 4, 5, 6, 7, 8])
print(np.sort(arr))
a= np.array([1, 2, 3])
b=np.array([4,5,6])
c = np.concatenate((a,b))
print(c)
x =np.array([[1,2], [3,4]])
y=np.array([[5,6]])
z = np.concatenate((x, y), axis=0)
print(z)

[1 2 3 4 5 6 7 8]
[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]


In [20]:
# Size and Shape of an array
# ndarray.ndim, ndarray.size, ndarray.shape
array_example = np.array([[[0,1,2,3], [4,5,6,7]], [[0,1,2,3], [4,5,6,7]], [[0,1,2,3], [4,5,6,7]]])
size_of_array = np.size(array_example)
shape_of_array = np.shape(array_example)
dimension_of_array = np.ndim(array_example)
print(size_of_array, shape_of_array, dimension_of_array)
      
print(array_example)


24 (3, 2, 4) 3
[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [30]:
# Reshaping an array
arr3 = np.arange(6)
arr3b= arr3.reshape(3,2)
arr3c= np.reshape(arr3, newshape=(1, 6),order='C')
print(arr3c)

[[0 1 2 3 4 5]]


In [ ]:
# How to convert 1D to 2D array(how to a new axis to an array).