In [1]:
import numpy as np

In [2]:
np1 = np.array([0,1 , 2, 3, 4, 5, 6, 7, 8, 9])
np1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np2 = np1[2: 6]
np2

array([2, 3, 4, 5])

In [11]:
# Return from something to the end of the array?
print(np1[3:])
print(np1[:-4])
print(np1[-3:-1:])

[3 4 5 6 7 8 9]
[0 1 2 3 4 5]
[7 8]


In [16]:
# steps
np3 = np1[1: 4: 2]
np4 = np1[:: 2]
np4

array([0, 2, 4, 6, 8])

In [27]:
# Create a 2d array
np5 = np.array([[0, 1, 2], [3, 4, 5]])
# pull out a single item
print(np5[0][2], np5[1][2])
# slice a 2d array
print(np5[0:2, 1:2])

2 5
[[1]
 [4]]
