In [3]:
import numpy as np

In [10]:
# Basic operations
a = np.array([20, 30, 40, 50])
b = np.arange(4)
c = a < 35
c

array([ True,  True, False, False])

In [16]:
A = np.array([[1, 1], [0, 1]])
B = np.array([[2, 0], [3, 4]])
# C = A * B  Element Wise
C = A @ B  # Matrix multplication
d = A.dot(B)  # another matrix product
d

array([[5, 4],
       [3, 4]])

In [27]:
# Some operations modify array in place 
rg = np.random.default_rng(1)  # create instance of default random number generator
a = np.ones((2, 3), dtype=int)
b = rg.random((2, 3))
a *=3
b += a # Add a to every unit of b (int => float)
# a += b # Add b to every unit of a (float => int) Error: UFuncTypeError

In [38]:
#  Upcasting: type of the result array
a = np.ones(3, dtype=int)
b = np.linspace(0, np.pi, 3)
c = a + b
c.dtype.name
d = np.exp(c * 1j)
d.dtype.name

'complex128'

In [42]:
# Unary Operations are implemented as methods of the ndarray
a = rg.random((2, 3))
a.sum()
a.min()
a.max()

0.9699254132161326

In [48]:
# By specifying the axis parameter you can apply an operation along the specified axis of the array
b = np.arange(12).reshape(3, 4)
b.sum(axis=0) # sum of each column
b.min(axis=1)  # min of each row
b.cumsum(axis=1)   # cum sum on each row

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

In [51]:
# Universal functions provides a family of natural functions
# Unviral functions are sin, cos, exp
B = np.arange(3)
np.exp(B)
np.sqrt(B)

array([1.        , 2.71828183, 7.3890561 ])