In [3]:
import numpy as np

In [10]:
# Basic operations
a = np.array([20, 30, 40, 50])
b = np.arange(4)
c = a < 35
c

array([ True,  True, False, False])

In [16]:
A = np.array([[1, 1], [0, 1]])
B = np.array([[2, 0], [3, 4]])
# C = A * B  Element Wise
C = A @ B  # Matrix multplication
d = A.dot(B)  # another matrix product
d

array([[5, 4],
       [3, 4]])

In [27]:
# Some operations modify array in place 
rg = np.random.default_rng(1)  # create instance of default random number generator
a = np.ones((2, 3), dtype=int)
b = rg.random((2, 3))
a *=3
b += a # Add a to every unit of b (int => float)
# a += b # Add b to every unit of a (float => int) Error: UFuncTypeError

In [38]:
#  Upcasting: type of the result array
a = np.ones(3, dtype=int)
b = np.linspace(0, np.pi, 3)
c = a + b
c.dtype.name
d = np.exp(c * 1j)
d.dtype.name

'complex128'

In [42]:
# Unary Operations are implemented as methods of the ndarray
a = rg.random((2, 3))
a.sum()
a.min()
a.max()

0.9699254132161326

In [48]:
# By specifying the axis parameter you can apply an operation along the specified axis of the array
b = np.arange(12).reshape(3, 4)
b.sum(axis=0) # sum of each column
b.min(axis=1)  # min of each row
b.cumsum(axis=1)   # cum sum on each row

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

In [53]:
# Universal functions provides a family of natural functions
# Unviral functions are sin, cos, exp
B = np.arange(3)
np.exp(B)
np.sqrt(B)
C = np.array([2., -1., 4.])
np.add(B, C)

array([2., 0., 6.])

In [61]:
# Indexing, slicing and iterating
a = np.arange(10)**3
a[2:5]
a[:6:2] = 1000 # from start to position 6, set every second element to 1000
a[::-1]
for i in a:
    print(i **(1/3.))

9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
5.0
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [75]:
# Multidimensional arrays
def f(x, y):
    return 10 * x + y
b = np.fromfunction(f, (5, 4), dtype=int)
b[2, 3]
print(b)
b[0:5, 1] # each row in the second column of b
b[:, 1]   # equivalent to the previous example
b[1:3, :] # each column in the second and third row
b[::-1]   # reverses the array
b[-1]  # last row

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]


array([[40, 41, 42, 43],
       [30, 31, 32, 33],
       [20, 21, 22, 23],
       [10, 11, 12, 13],
       [ 0,  1,  2,  3]])

In [80]:
c = np.array([[[0, 1, 2], [10, 12, 13]],
              [[100, 101, 102], [110, 112, 113]]]) # a 3D array (two stacked 2D arrays)
c.shape
c[1, ...] # c[1]
c[..., 2] # c[:, :, 2]

array([[  2,  13],
       [102, 113]])

In [81]:
# Iterating over multidimensional array
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [82]:
# flatten the b array
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


In [ ]:
# Shape Manipulation

In [86]:
# changing the shape of an array
a =  np.floor(10 * rg.random((3, 4)))
a.shape


(3, 4)

In [94]:
# This three comands all return a modified array
# ravel(), reshape(), T()
a.ravel()  #returns the array, flattened
a.reshape(6, 2)  # returns the array with a modified shape
a.T.shape

(4, 3)

In [99]:
# Stacking together differnt array
a = np.floor(10 * rg.random((2, 2)))
b = np.floor(10 * rg.random((2, 2)))
print(a)
print(b)
np.vstack((a, b))  #stack two numpy array vertically
np.hstack((a, b))  #stack two numpy array horizontally

[[5. 1.]
 [9. 2.]]
[[2. 0.]
 [2. 7.]]


array([[5., 1., 2., 0.],
       [9., 2., 2., 7.]])

In [109]:
from numpy import newaxis
np.column_stack((a, b))     # with 2D arrays
# column_stack stacks 1D arrays into 2D arrays


a =np.array([4., 2.])
b = np.array([3., 8.])
np.column_stack((a, b))    # returns a 2D array
np.hstack((a, b))     # The result is different here
a[:, newaxis] # views 'a' as a 2D array
np.hstack((a[:, newaxis], b[:,newaxis]))


array([[4., 3.],
       [2., 8.]])

# Copies and views

In [6]:
# No copies at all
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]])
bac = a       # No new object is created 
bac is a      # a and bac are two names for the same ndarray object

True

In [11]:
import numpy as np
def f(x):
    print(id(x))

id(a)   # id is a unique identifier for an object
f(a)

2872870769872


In [32]:
# Differnt array objects can share the same  data.
# The view method creates array object that looks at the same data
c = a.view()
c is a    # false
c.base is a  # True
c.flags.owndata  # false

c = c.reshape((2, 6))
c[0, 4] = 1234
s = a[:, 1:3] 
s[:]  = 10  # s[:] is a view of s. Note the differnce between s = 10 and s[:] = 10
s
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

In [38]:
# Deep copy
d = a.copy()  # a new data object with new data is created
d is a # false
d.base is a  # d doesn't share anything with a
d[0, 0] = 9999
d

array([[9999,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

In [43]:
a = np.arange(int(1e8))
b = a[:100].copy()
del a   # the memory of `a` can be released.
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

FUnctions and Methods overview