In [3]:
import numpy as np

In [10]:
# Basic operations
a = np.array([20, 30, 40, 50])
b = np.arange(4)
c = a < 35
c

array([ True,  True, False, False])

In [16]:
A = np.array([[1, 1], [0, 1]])
B = np.array([[2, 0], [3, 4]])
# C = A * B  Element Wise
C = A @ B  # Matrix multplication
d = A.dot(B)  # another matrix product
d

array([[5, 4],
       [3, 4]])

In [27]:
# Some operations modify array in place 
rg = np.random.default_rng(1)  # create instance of default random number generator
a = np.ones((2, 3), dtype=int)
b = rg.random((2, 3))
a *=3
b += a # Add a to every unit of b (int => float)
# a += b # Add b to every unit of a (float => int) Error: UFuncTypeError

In [38]:
#  Upcasting: type of the result array
a = np.ones(3, dtype=int)
b = np.linspace(0, np.pi, 3)
c = a + b
c.dtype.name
d = np.exp(c * 1j)
d.dtype.name

'complex128'

In [42]:
# Unary Operations are implemented as methods of the ndarray
a = rg.random((2, 3))
a.sum()
a.min()
a.max()

0.9699254132161326

In [48]:
# By specifying the axis parameter you can apply an operation along the specified axis of the array
b = np.arange(12).reshape(3, 4)
b.sum(axis=0) # sum of each column
b.min(axis=1)  # min of each row
b.cumsum(axis=1)   # cum sum on each row

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

In [53]:
# Universal functions provides a family of natural functions
# Unviral functions are sin, cos, exp
B = np.arange(3)
np.exp(B)
np.sqrt(B)
C = np.array([2., -1., 4.])
np.add(B, C)

array([2., 0., 6.])

In [61]:
# Indexing, slicing and iterating
a = np.arange(10)**3
a[2:5]
a[:6:2] = 1000 # from start to position 6, set every second element to 1000
a[::-1]
for i in a:
    print(i **(1/3.))

9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
5.0
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [75]:
# Multidimensional arrays
def f(x, y):
    return 10 * x + y
b = np.fromfunction(f, (5, 4), dtype=int)
b[2, 3]
print(b)
b[0:5, 1] # each row in the second column of b
b[:, 1]   # equivalent to the previous example
b[1:3, :] # each column in the second and third row
b[::-1]   # reverses the array
b[-1]  # last row

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]


array([[40, 41, 42, 43],
       [30, 31, 32, 33],
       [20, 21, 22, 23],
       [10, 11, 12, 13],
       [ 0,  1,  2,  3]])

In [80]:
c = np.array([[[0, 1, 2], [10, 12, 13]],
              [[100, 101, 102], [110, 112, 113]]]) # a 3D array (two stacked 2D arrays)
c.shape
c[1, ...] # c[1]
c[..., 2] # c[:, :, 2]

array([[  2,  13],
       [102, 113]])

In [81]:
# Iterating over multidimensional array
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [82]:
# flatten the b array
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


In [ ]:
# Shape Manipulation

In [86]:
# changing the shape of an array
a =  np.floor(10 * rg.random((3, 4)))
a.shape


(3, 4)

In [94]:
# This three comands all return a modified array
# ravel(), reshape(), T()
a.ravel()  #returns the array, flattened
a.reshape(6, 2)  # returns the array with a modified shape
a.T.shape

(4, 3)

In [99]:
# Stacking together differnt array
a = np.floor(10 * rg.random((2, 2)))
b = np.floor(10 * rg.random((2, 2)))
print(a)
print(b)
np.vstack((a, b))  #stack two numpy array vertically
np.hstack((a, b))  #stack two numpy array horizontally

[[5. 1.]
 [9. 2.]]
[[2. 0.]
 [2. 7.]]


array([[5., 1., 2., 0.],
       [9., 2., 2., 7.]])