In [2]:
import numpy as np

In [3]:
a = np.arange(10)
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [9]:
a = np.diag(np.arange(3))
a[1, 1] = 5
a

array([[0, 0, 0],
       [0, 5, 0],
       [0, 0, 2]])

In [16]:
a = np.arange(10)
a[2:9:3]
a[:4]
print(a[3:])
a[::2]

[3 4 5 6 7 8 9]


array([0, 2, 4, 6, 8])

In [23]:
# Combining assignmnt and slicing
b = np.arange(5)

b[5:] = b[::-1]

ValueError: could not broadcast input array from shape (5,) into shape (0,)

In [33]:
bve = np.arange(1) + np.arange(0,51,10)[:, np.newaxis]
bve

array([[ 0],
       [10],
       [20],
       [30],
       [40],
       [50]])

In [32]:
cve = np.arange(12).reshape((4,3))
cve

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])