In [ ]:
# Elementwise operations
# Basic reduction
# Broadcasting
# Array shape manipulation
# Sorting data
# summary

In [36]:
# Elementwise operations

# with scalars
a = np.array([1, 2,3,4])
a + 1
a * 3

array([ 3,  6,  9, 12])

In [44]:
b = np.ones(4) + 1
print(a, b)
a - b
a * b



[1 2 3 4] [2. 2. 2. 2.]


array([2., 4., 6., 8.])

In [45]:
j =  np.arange(5)
2 ** (j + 1) - j

array([ 2,  3,  6, 13, 28])

In [46]:
a = np.arange(10000)
%timeit a + 1

54.5 µs ± 8.16 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [47]:
# Not a matrix multiplication
c = np.ones((3, 3))
c * c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [48]:
# Matrix multiplication
c @ c

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])